added tests for existing functionality
wixplosives/codux-core pull request #1219
Opened 2024-10-07 15:39 UTC by nadav-ab

2024-10-09 06:53 UTC, idoros requested changes

2024-10-09 06:53 UTC, idoros commented on packages/define-remix-app/test/test-cases/roots.ts
> +    debugger;
leftover

2024-10-09 06:53 UTC, idoros commented on packages/define-remix-app/test/define-remix.spec.ts
> +                    .to.include('Layout|App|About:About loaded data-loaded extra');
Consider testing the initial render without the delayed data to ensure it behaves correctly when the data is pending

2024-10-09 06:53 UTC, idoros commented on packages/define-remix-app/test/define-remix.spec.ts
> +                    .to.include('Layout!App|About!AboutUs!');
Is this going to contain `App|`?

2024-10-09 06:53 UTC, idoros commented on esbuild.config.js
> +const utilModulePath = require.resolve(`./micro-util-nofill.js`);
Why are these test polyfills defined in separate files instead of being inlined directly here?

2024-10-10 07:49 UTC, nadav-ab commented on packages/define-remix-app/test/define-remix.spec.ts
> +                    .to.include('Layout|App|About:About loaded data-loaded extra');
it is'nt yet

2024-10-10 07:50 UTC, nadav-ab commented on packages/define-remix-app/test/define-remix.spec.ts
> +                    .to.include('Layout!App|About!AboutUs!');
no

2024-10-10 07:51 UTC, nadav-ab commented on esbuild.config.js
> +const utilModulePath = require.resolve(`./micro-util-nofill.js`);
we want to ideally export all the polyfills used in codux online here

2024-10-10 08:15 UTC, idoros commented on packages/define-remix-app/test/define-remix.spec.ts
> +                    .to.include('Layout|App|About:About loaded data-loaded extra');
It's rendered with just the "immidiateData" before the "delayedData" is resolved

2024-10-10 08:15 UTC, idoros commented on esbuild.config.js
> +const utilModulePath = require.resolve(`./micro-util-nofill.js`);
Move these APIs into a dedicated folder called something like `node-lib-placeholders` and rename `micro-util-nofill.js` to `util.js`.

Atm, these files are not exported from any package, as they are located in the root of the repository and are not set as in any `package.json files` so maybe place this folder in `app-core`.

2024-10-10 08:27 UTC, nadav-ab commented on packages/define-remix-app/test/define-remix.spec.ts
> +                    .to.include('Layout|App|About:About loaded data-loaded extra');
should be, not implemented yet

2024-10-10 08:31 UTC, nadav-ab commented on esbuild.config.js
> +const utilModulePath = require.resolve(`./micro-util-nofill.js`);
i will in a separate PR, need to think how to do that and avoid a separate build process

2024-10-10 08:54 UTC, merged